### ISSUE TITLE
[DOCS] Add issue/PR templates

### ISSUE THREAD

**Issue by Panquesito7** [lunatic-fox/eps2img#1]
Title explains it all. :)
I'd like to work on this as well.

**Comment by lunatic-fox** [comment]
Thank you! 🙂
It will be added in the next commit. 📑🚀

**Comment by lunatic-fox** [comment]
Hello again!
I've made these changes in documentation: [***documentation branch***](https://github.com/lunatic-fox/eps2img/tree/documentation).
If you want you can make pull requests to that branch. 👍🏼

**Comment by lunatic-fox** [comment]
All done! 🚀
