### ISSUE TITLE
Add support for converting to PDF

### ISSUE THREAD

**Issue by Snailedlt** [lunatic-fox/eps2img#2]
Would be neat if it was possible to convert to .pdf files instead. Some PDF formats are scalable (vector graphics), so if the .eps was also scalable, that would be great

**Comment by lunatic-fox** [comment]
Thank you that's a great idea! 👏🏼
I think that's totally possible.
I'll be trying to implement the support to converting EPS to PDF files soon! 🚀

**Comment by Snailedlt** [comment]
Neat!
You might be able to use some code from this vscode extension: https://github.com/ahnafnafee/PostScript-Preview

**Comment by lunatic-fox** [comment]
**Support to PDF format added!**
- Commit: https://github.com/lunatic-fox/eps2img/commit/7d816cbfec92af0d4046bd5d05836e666d441548

I've just needed to edit a few lines of the original code. 🙂
If everything is ok, I'll be closing this issue.

**Comment by lunatic-fox** [comment]
> Neat! You might be able to use some code from this vscode extension: https://github.com/ahnafnafee/PostScript-Preview

Thanks for the suggestion! 😃
> PS: I'd totally forgot that `.pdf` is also a vector format. 😅
  Therefore, it's importable to Inkscape, for instance.

**Comment by lunatic-fox** [comment]
All done! 🚀
